version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - db_data:/app/db  # Adiciona um volume para persistir dados do banco de dados
    ports:
      - "8001:8000"
volumes:
  db_data:  # Define o volume para persistir dados do banco de dados